# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_form_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_edit(object):
    def setupUi(self, form_edit):
        form_edit.setObjectName("form_edit")
        form_edit.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(form_edit)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 351, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_soyisim_ekle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_soyisim_ekle.setObjectName("lineEdit_soyisim_ekle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_soyisim_ekle)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_tel_ekle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_tel_ekle.setObjectName("lineEdit_tel_ekle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tel_ekle)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_eposta_ekle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_eposta_ekle.setObjectName("lineEdit_eposta_ekle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_eposta_ekle)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_tarih_ekle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_tarih_ekle.setObjectName("lineEdit_tarih_ekle")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tarih_ekle)
        self.lineEdit_isim_ekle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_isim_ekle.setObjectName("lineEdit_isim_ekle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_isim_ekle)
        self.btn_kisiyi_ekle = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_kisiyi_ekle.setObjectName("btn_kisiyi_ekle")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_kisiyi_ekle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(form_edit)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(form_edit)
        QtCore.QMetaObject.connectSlotsByName(form_edit)
        form_edit.setTabOrder(self.lineEdit_isim_ekle, self.lineEdit_soyisim_ekle)
        form_edit.setTabOrder(self.lineEdit_soyisim_ekle, self.lineEdit_tel_ekle)
        form_edit.setTabOrder(self.lineEdit_tel_ekle, self.lineEdit_eposta_ekle)
        form_edit.setTabOrder(self.lineEdit_eposta_ekle, self.lineEdit_tarih_ekle)
        form_edit.setTabOrder(self.lineEdit_tarih_ekle, self.btn_kisiyi_ekle)

    def retranslateUi(self, form_edit):
        _translate = QtCore.QCoreApplication.translate
        form_edit.setWindowTitle(_translate("form_edit", "Kişi Düzenle"))
        self.label.setText(_translate("form_edit", "İsim"))
        self.label_2.setText(_translate("form_edit", "Soyisim"))
        self.label_3.setText(_translate("form_edit", "Telefon Numarası"))
        self.label_4.setText(_translate("form_edit", "E-Posta"))
        self.label_5.setText(_translate("form_edit", "Doğum Tarihi"))
        self.btn_kisiyi_ekle.setText(_translate("form_edit", "Kişiyi Kaydet"))
        self.label_6.setText(_translate("form_edit", "Kişi Adı"))
